spring:
  web:
    resources:
      cache:
        period: PT2H
      chain:
        cache: true
        strategy:
          content:
            enabled: true

logging:
  config: classpath:log4j2-production.xml
  file:
    path: log
